[tool.bumpversion]
current_version = "0.0.25"
commit = true
tag = true
parse = "(?P<major>\\d+)\\.(?P<minor>\\d+)\\.(?P<patch>\\d+)"
serialize = ["{major}.{minor}.{patch}"]
message = "Bump: {current_version} â†’ {new_version}"
tag_name = "v{new_version}"
