[tool.bumpversion]
current_version = "0.4.0"
commit = true
tag = false
parse = "(?P<major>\\d+)\\.(?P<minor>\\d+)\\.(?P<patch>\\d+)"
serialize = ["{major}.{minor}.{patch}"]
message = "Bump: {current_version} â†’ {new_version}"
tag_name = "v{new_version}"

[[tool.bumpversion.files]]
filename = "cmd/root.go"
search = "version            = \"{current_version}\""
replace = "version            = \"{new_version}\""
