repos:
  - repo: local
    hooks:
      - id: make-docs
        name: Generate CLI documentation
        entry: bash -c 'make docs && git diff --exit-code docs/'
        language: system
        pass_filenames: false
        always_run: false
        stages: [pre-commit]
        files: '\.go$'

      - id: check-go-mod-tidy
        name: Check go.mod is tidy
        entry: go mod tidy
        language: system
        pass_filenames: false
        always_run: false
        stages: [pre-commit]
        files: ^go\.mod$

      - id: run-unit-tests
        name: Run unit tests
        entry: go test ./...
        language: system
        pass_filenames: false
        always_run: false
        stages: [pre-commit]
        files: '\.go$'
